//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonicTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicTheHedgehog1CheckedItems {
            get {
                return ((string)(this["SonicTheHedgehog1CheckedItems"]));
            }
            set {
                this["SonicTheHedgehog1CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicTheHedgehog2CheckedItems {
            get {
                return ((string)(this["SonicTheHedgehog2CheckedItems"]));
            }
            set {
                this["SonicTheHedgehog2CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicCDCheckedItems {
            get {
                return ((string)(this["SonicCDCheckedItems"]));
            }
            set {
                this["SonicCDCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sonic3AndKnucklesCheckedItems {
            get {
                return ((string)(this["Sonic3AndKnucklesCheckedItems"]));
            }
            set {
                this["Sonic3AndKnucklesCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicAndTailsCheckedItems {
            get {
                return ((string)(this["SonicAndTailsCheckedItems"]));
            }
            set {
                this["SonicAndTailsCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicAndTails2CheckedItems {
            get {
                return ((string)(this["SonicAndTails2CheckedItems"]));
            }
            set {
                this["SonicAndTails2CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KnucklesChaotixCheckedItems {
            get {
                return ((string)(this["KnucklesChaotixCheckedItems"]));
            }
            set {
                this["KnucklesChaotixCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TailsAdventureCheckedItems {
            get {
                return ((string)(this["TailsAdventureCheckedItems"]));
            }
            set {
                this["TailsAdventureCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicBlastCheckedItems {
            get {
                return ((string)(this["SonicBlastCheckedItems"]));
            }
            set {
                this["SonicBlastCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sonic3DBlastCheckedItems {
            get {
                return ((string)(this["Sonic3DBlastCheckedItems"]));
            }
            set {
                this["Sonic3DBlastCheckedItems"] = value;
            }
        }
    }
}
