//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonicTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicTheHedgehog1CheckedItems {
            get {
                return ((string)(this["SonicTheHedgehog1CheckedItems"]));
            }
            set {
                this["SonicTheHedgehog1CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicTheHedgehog2CheckedItems {
            get {
                return ((string)(this["SonicTheHedgehog2CheckedItems"]));
            }
            set {
                this["SonicTheHedgehog2CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicCDCheckedItems {
            get {
                return ((string)(this["SonicCDCheckedItems"]));
            }
            set {
                this["SonicCDCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sonic3AndKnucklesCheckedItems {
            get {
                return ((string)(this["Sonic3AndKnucklesCheckedItems"]));
            }
            set {
                this["Sonic3AndKnucklesCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicAndTailsCheckedItems {
            get {
                return ((string)(this["SonicAndTailsCheckedItems"]));
            }
            set {
                this["SonicAndTailsCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicAndTails2CheckedItems {
            get {
                return ((string)(this["SonicAndTails2CheckedItems"]));
            }
            set {
                this["SonicAndTails2CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KnucklesChaotixCheckedItems {
            get {
                return ((string)(this["KnucklesChaotixCheckedItems"]));
            }
            set {
                this["KnucklesChaotixCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TailsAdventureCheckedItems {
            get {
                return ((string)(this["TailsAdventureCheckedItems"]));
            }
            set {
                this["TailsAdventureCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicBlastCheckedItems {
            get {
                return ((string)(this["SonicBlastCheckedItems"]));
            }
            set {
                this["SonicBlastCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sonic3DBlastCheckedItems {
            get {
                return ((string)(this["Sonic3DBlastCheckedItems"]));
            }
            set {
                this["Sonic3DBlastCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreferredFraction {
            get {
                return ((bool)(this["PreferredFraction"]));
            }
            set {
                this["PreferredFraction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicPocketAdventureCheckedItems {
            get {
                return ((string)(this["SonicPocketAdventureCheckedItems"]));
            }
            set {
                this["SonicPocketAdventureCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicAdventureCheckedItems {
            get {
                return ((string)(this["SonicAdventureCheckedItems"]));
            }
            set {
                this["SonicAdventureCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicAdventure2CheckedItems {
            get {
                return ((string)(this["SonicAdventure2CheckedItems"]));
            }
            set {
                this["SonicAdventure2CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicAdvanceCheckedItems {
            get {
                return ((string)(this["SonicAdvanceCheckedItems"]));
            }
            set {
                this["SonicAdvanceCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicAdvance2CheckedItems {
            get {
                return ((string)(this["SonicAdvance2CheckedItems"]));
            }
            set {
                this["SonicAdvance2CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicHeroesCheckedItems {
            get {
                return ((string)(this["SonicHeroesCheckedItems"]));
            }
            set {
                this["SonicHeroesCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicAdvance3CheckedItems {
            get {
                return ((string)(this["SonicAdvance3CheckedItems"]));
            }
            set {
                this["SonicAdvance3CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicRushCheckedItems {
            get {
                return ((string)(this["SonicRushCheckedItems"]));
            }
            set {
                this["SonicRushCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShadowTheHedgehogCheckedItems {
            get {
                return ((string)(this["ShadowTheHedgehogCheckedItems"]));
            }
            set {
                this["ShadowTheHedgehogCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sonic06CheckedItems {
            get {
                return ((string)(this["Sonic06CheckedItems"]));
            }
            set {
                this["Sonic06CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicRushAdventureCheckedItems {
            get {
                return ((string)(this["SonicRushAdventureCheckedItems"]));
            }
            set {
                this["SonicRushAdventureCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicSecretRingsCheckedItems {
            get {
                return ((string)(this["SonicSecretRingsCheckedItems"]));
            }
            set {
                this["SonicSecretRingsCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicUnleashedPS2CheckedItems {
            get {
                return ((string)(this["SonicUnleashedPS2CheckedItems"]));
            }
            set {
                this["SonicUnleashedPS2CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicUnleashedPS3CheckedItems {
            get {
                return ((string)(this["SonicUnleashedPS3CheckedItems"]));
            }
            set {
                this["SonicUnleashedPS3CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicBlackNightCheckedItems {
            get {
                return ((string)(this["SonicBlackNightCheckedItems"]));
            }
            set {
                this["SonicBlackNightCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sonic4E1CheckedItems {
            get {
                return ((string)(this["Sonic4E1CheckedItems"]));
            }
            set {
                this["Sonic4E1CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicColorsCheckedItems {
            get {
                return ((string)(this["SonicColorsCheckedItems"]));
            }
            set {
                this["SonicColorsCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicGenerationsCheckedItems {
            get {
                return ((string)(this["SonicGenerationsCheckedItems"]));
            }
            set {
                this["SonicGenerationsCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sonic4E2CheckedItems {
            get {
                return ((string)(this["Sonic4E2CheckedItems"]));
            }
            set {
                this["Sonic4E2CheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicLostWorldCheckedItems {
            get {
                return ((string)(this["SonicLostWorldCheckedItems"]));
            }
            set {
                this["SonicLostWorldCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicBoomLyricCheckedItems {
            get {
                return ((string)(this["SonicBoomLyricCheckedItems"]));
            }
            set {
                this["SonicBoomLyricCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicBoomShatteredCrystalCheckedItems {
            get {
                return ((string)(this["SonicBoomShatteredCrystalCheckedItems"]));
            }
            set {
                this["SonicBoomShatteredCrystalCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicBoomFireIceCheckedItems {
            get {
                return ((string)(this["SonicBoomFireIceCheckedItems"]));
            }
            set {
                this["SonicBoomFireIceCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicManiaCheckedItems {
            get {
                return ((string)(this["SonicManiaCheckedItems"]));
            }
            set {
                this["SonicManiaCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicForcesCheckedItems {
            get {
                return ((string)(this["SonicForcesCheckedItems"]));
            }
            set {
                this["SonicForcesCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicColorsUltimateCheckedItems {
            get {
                return ((string)(this["SonicColorsUltimateCheckedItems"]));
            }
            set {
                this["SonicColorsUltimateCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicFrontiersCheckedItems {
            get {
                return ((string)(this["SonicFrontiersCheckedItems"]));
            }
            set {
                this["SonicFrontiersCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicSuperstarsCheckedItems {
            get {
                return ((string)(this["SonicSuperstarsCheckedItems"]));
            }
            set {
                this["SonicSuperstarsCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicDreamTeamCheckedItems {
            get {
                return ((string)(this["SonicDreamTeamCheckedItems"]));
            }
            set {
                this["SonicDreamTeamCheckedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonicShadowGenerationsCheckedItems {
            get {
                return ((string)(this["SonicShadowGenerationsCheckedItems"]));
            }
            set {
                this["SonicShadowGenerationsCheckedItems"] = value;
            }
        }
    }
}
